### PR TITLE
fix: remove confusing naming visible

### PR DESCRIPTION
**Pull request by alswl**
Rename visible to available to avoid ambiguity as to whether visible is visible on the UI or available on the data.

API changes are backward compatible.

### CODE REVIEW

**Comment by alswl** [comment]
It is strange how a mere function name refactoring can cause a decrease in test coverage. I'll have to look into it.

**Comment by alswl** [comment]
It is strange how a mere function name refactoring can cause a decrease in test coverage. I'll have to look into it.

**Comment by Evertras** [comment]
I agree that `VisibleRows` is potentially confusing, but I don't know if `AvailableRows` is better enough to warrant a breaking API change.  I understand that you've tied the old name to the new as pass-through functions, but to me this is still a breaking change and I don't necessarily want to deprecate something lightly.

I think the better solution for now might just be to very clearly document the meaning of `VisibleRows`, if it's currently unclear.

**Comment by Evertras** [comment]
> It is strange how a mere function name refactoring can cause a decrease in test coverage. I'll have to look into it.

Also to clarify this mystery, it's because you've added the passthrough functions.  You're not just renaming the function, you're adding new functions and keeping the legacy names around, even if technically they're just one line of code to call the new functions.

**Pull request closed without merging**
