### PR TITLE
Add function to set the highlighted row - fixes issue #42

### PR DESCRIPTION
**Pull request by gairadzi**
Allow setting which row will be highlighted by passing its index

### CODE REVIEW

**Comment by gairadzi** [comment]
Sure, sounds good.
Do you prefer me to move it to the `options.go` file?

**Comment by Evertras** [comment]
Yep that LGTM, just need to fix the lint issue (running `make fmt` should do it) and a quick test for coverage would be great.

**Comment by Evertras** [comment]
(Quick link to #42 since the title doesn't trigger Github linking the issue/PR)

**Review by Evertras — APPROVED** [review]

**Comment by Evertras** [comment]
LGTM, the tiny dip in coverage is fine.  I'll add a test or two later.  Thanks for the contribution!

**Pull request merged**
